### ISSUE TITLE
Program output updated?

### ISSUE THREAD

**Issue by hunuyolau** [vladimiriii/jsonify-it#3]
I have been using your web tool to convert CSV to JSON. I just found that the output of your JSON converter is changed (i.e. the "count" field moved from start of the layer to last of the layer and layer's name change from "id" to "name"). is there a new program implementing?

**Comment by vladimiriii** [comment]
Hey, as you can see from this repo, no changes have been made for some time (to my great embarrassment...). In regards to the two issues you mention:

1. There is a level of randomness to which 'order' the keys will be in the output JSON, but that is because a JSON object ["is an unordered set of name/value pairs"](https://www.json.org/json-en.html). {"a": 1, "b": 2} is the same as {"b": 2, "a": 1}. You should never rely on the order of JSON keys being static. 

2. As for the 'id'/'name' issue, it can change based on the options you select. For example, did you specify an index column, what base structure did you select, etc. But the same options _will_ generate the same output.

**Comment by hunuyolau** [comment]
thx a lot.

For 1, previously the output is like this
![image](https://user-images.githubusercontent.com/59041961/72579806-1fde9a00-3915-11ea-83b7-afd5fc5d5103.png)
 currently, the change is this
![image](https://user-images.githubusercontent.com/59041961/72579890-62a07200-3915-11ea-8270-4701d7106a3c.png)
i didn't make any changes my level.


For 2, let me check again
